"""Seoulgaok BIM core — Python types, IO, operations, validators."""

from .config import build_options, load_overrides as load_config
from .errors import CompileError, CompileErrorType
from .site_filter import (
    SiteFilterNotConfigured,
    build_where as build_site_where,
    load_criteria as load_site_criteria,
)
from .options import (
    BuildOptions,
    Concrete,
    Core,
    Financing,
    Massing,
    GroundFloor,
    Parking,
    RegulationOverrides,
    Schedule,
    Structure,
    UnitSpec,
    Windows,
)
from .types import (
    BeamUserData,
    BufferAttributeData,
    BufferGeometryData,
    ColumnUserData,
    CoreLayout,
    CoveringUserData,
    DoorUserData,
    FloorData,
    FloorGeometry,
    FloorPlan,
    HostWallRef,
    MaterialLayer,
    RailingUserData,
    Scheme,
    SchemeData,
    SlabUserData,
    StairLayoutItem,
    StairMemberUserData,
    StairUserData,
    SurroundingBuilding,
    SurroundingData,
    SurroundingGeometry,
    Unit,
    UnitAreaBreakdown,
    UnitData,
    UnitGeometry,
    UnitRecord,
    UnitRoom,
    WallUserData,
    WindowUserData,
)

__version__ = "0.0.13"

__all__ = [
    # Output types (Scheme 등)
    "BufferAttributeData",
    "BufferGeometryData",
    "FloorData",
    "FloorGeometry",
    "FloorPlan",
    "Scheme",
    "SchemeData",
    "SurroundingBuilding",
    "SurroundingData",
    "SurroundingGeometry",
    "Unit",
    "UnitData",
    "UnitGeometry",
    # units.json 실계약 (생성기 직렬화)
    "UnitRecord",
    "UnitAreaBreakdown",
    "UnitRoom",
    # scheme 공간 계약
    "CoreLayout",
    # LOD300 userData (kind 판별)
    "MaterialLayer",
    "HostWallRef",
    "WallUserData",
    "SlabUserData",
    "ColumnUserData",
    "BeamUserData",
    "DoorUserData",
    "WindowUserData",
    "CoveringUserData",
    "RailingUserData",
    "StairUserData",
    "StairMemberUserData",
    "StairLayoutItem",
    # Input options (BuildOptions 등)
    "BuildOptions",
    "Massing",
    "UnitSpec",
    "Core",
    "Structure",
    "Windows",
    "GroundFloor",
    "Parking",
    "Concrete",
    "Schedule",
    "Financing",
    "RegulationOverrides",
    # CompileError (CSP 명제 위반)
    "CompileError",
    "CompileErrorType",
    # 원클릭 대상 필지 필터
    "build_options",
    "load_config",
    "SiteFilterNotConfigured",
    "build_site_where",
    "load_site_criteria",
]
